version: '3'

services:
        app_fe: 
          build: 
            context: .
            dockerfile: Dockerfile.dev
          ports:
            - "3000:3000"
          volumes: 
            - .:/usr/src/app
